config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("records/", include("records.urls", namespace="records")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path
from records.apps import RecordsConfig
from records.views import (
    EntryListView,
    PrivateEntryListView,
    PastEntryListView,
    PresentEntryListView,
    FutureEntryListView,
    EntryCreateView,
    EntryUpdateView,
    EntryDetailView,
    EntryDeleteView,
    ObjectiveUpdateView,
    ObjectiveDeleteView,
    ObjectiveCreateView,
)

app_name = RecordsConfig.name

urlpatterns = [
    # ЗАПИСИ
    path("list/", EntryListView.as_view(), name="list"),
    path("private_list/", PrivateEntryListView.as_view(), name="private_list"),
    path("past_list/", PastEntryListView.as_view(), name="past_list"),
    path("present_list/", PresentEntryListView.as_view(), name="present_list"),
    path("future_list/", FutureEntryListView.as_view(), name="future_list"),
    path("create/", EntryCreateView.as_view(), name="create"),
    path("update/<int:pk>/", EntryUpdateView.as_view(), name="update"),
    path("detail/<int:pk>/", EntryDetailView.as_view(), name="detail"),
    path("delete/<int:pk>/", EntryDeleteView.as_view(), name="delete"),
    # ЗАДАЧИ
    path("create_obj/", ObjectiveCreateView.as_view(), name="create_obj"),
    path("update_obj/<int:pk>/", ObjectiveUpdateView.as_view(), name="update_obj"),
    path("delete_obj/<int:pk>/", ObjectiveDeleteView.as_view(), name="delete_obj"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView

app_name = UsersConfig.name
urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="check_email"),
    path("update/", UserUpdateView.as_view(), name="update"),
]

records/models.py
from datetime import datetime

from django.db import models

from users.models import User


class Entry(models.Model):
    """Модель записей в дневник"""

    user = models.ForeignKey(
        User, verbose_name="Владелец", on_delete=models.CASCADE, blank=True, null=True
    )
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    description = models.TextField(verbose_name="Описание", blank=True, null=True)

    is_private = models.BooleanField(default=False, verbose_name="Личное")
    is_purpose = models.BooleanField(default=False, verbose_name="Цель")
    last_viewed = models.BooleanField(default=False)

    PAST = "достигнута"
    PRESENT = "в процессе"
    FUTURE = "в планах"

    STATUS_CHOICES = (
        (PAST, "достигнута"),
        (PRESENT, "в процессе"),
        (FUTURE, "в планах"),
    )

    status = models.CharField(
        max_length=150,
        verbose_name="Статус",
        choices=STATUS_CHOICES,
        blank=True,
        null=True,
    )
    start_time = models.DateTimeField(
        verbose_name="Дата и время начала", default=datetime.now()
    )
    end_time = models.DateTimeField(
        verbose_name="Дата и время окончания", blank=True, null=True
    )

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

        ordering = ("start_time",)


class Objective(models.Model):
    """Модель задач"""

    title = models.CharField(max_length=200, verbose_name="Название")
    description = models.TextField(verbose_name="Описание", blank=True, null=True)
    time = models.DateTimeField(verbose_name="Начало решения", default=datetime.now())

    is_complete = models.BooleanField(default=False, verbose_name=" ")
    entry = models.ForeignKey(
        Entry,
        on_delete=models.CASCADE,
        verbose_name="Цель",
        related_name="objectives",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"

        ordering = (
            "is_complete",
            "time",
        )

records/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit
from django.forms import ModelForm
from records.models import Entry, Objective


class EntryCreateForm(ModelForm):
    """Форма для создания"""

    class Meta:
        model = Entry
        exclude = ("status",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_read_only = True
        self.helper.form_class = "border p-8"
        self.helper.layout = Layout(
            Div(
                Div("is_purpose", css_class="md:w-[10%]"),
                Div("is_private", css_class="md:w-[80%]"),
                css_class="md:flex md:justify-between",
            ),
            "title",
            "description",
            "start_time",
            "end_time",
            Submit(
                "submit",
                "Сохранить",
                css_class="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2",
            ),
        )


class EntryUpdateForm(ModelForm):
    """Форма для редактирования"""

    class Meta:
        model = Entry
        exclude = (
            "status",
            "is_purpose",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "border p-8"
        self.helper.layout = Layout(
            Div(
                Div("is_private", css_class="md:w-[80%]"),
                css_class="md:flex md:justify-between",
            ),
            "title",
            "description",
            "start_time",
            "end_time",
            Submit(
                "submit",
                "Сохранить",
                css_class="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2",
            ),
        )


class ObjectiveForm(ModelForm):
    """Модель задачи"""

    class Meta:
        model = Objective
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "border p-8"
        self.helper.layout = Layout(
            Div(
                Div("title", css_class="md:w-[40%]"),
                Div("is_complete", css_class="md:w-[90%]"),
                css_class="md:flex md:justify-between",
            ),
            "description",
            "time",
        )


class ObjectiveCreateForm(ModelForm):
    """Модель создания и изменения задачи"""

    class Meta:
        model = Objective
        fields = "__all__"

    # def clean(self):
    #     cleaned_data = super().clean()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "border p-8"
        self.helper.layout = Layout(
            Div(
                Div("title", css_class="md:w-[40%]"),
                Div("is_complete", css_class="md:w-[90%]"),
                css_class="md:flex md:justify-between",
            ),
            "description",
            "time",
            Submit(
                "submit",
                "Сохранить",
                css_class="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2",
            ),
        )

records/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
)
from django.db.models import Q
from records.forms import (
    EntryCreateForm,
    EntryUpdateForm,
    ObjectiveForm,
    ObjectiveCreateForm,
)
from records.models import Entry, Objective
from django.http import Http404


#  ЗАПИСИ
class PrivateEntryListView(LoginRequiredMixin, ListView):
    """Вывод списка личных записей"""

    model = Entry
    template_name = "records/list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        queryset = queryset.filter(Q(is_private=True) & Q(user=user))

        return queryset


class PastEntryListView(LoginRequiredMixin, ListView):
    """Вывод списка достигнутых целей"""

    model = Entry
    template_name = "records/list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        queryset = queryset.filter(is_purpose=True, status="PAST", user=user)

        return queryset


class PresentEntryListView(LoginRequiredMixin, ListView):
    """Вывод списка целей, который находятся в процессе достижения"""

    model = Entry
    template_name = "records/list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        queryset = queryset.filter(is_purpose=True, status="PRESENT", user=user)

        return queryset


class FutureEntryListView(LoginRequiredMixin, ListView):
    """Вывод списка целей, которые предстоит достичь"""

    model = Entry
    template_name = "records/list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        queryset = queryset.filter(is_purpose=True, status="FUTURE", user=user)

        return queryset


class EntryListView(LoginRequiredMixin, ListView):
    """Просмотре всех записей пользователя"""

    model = Entry

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        queryset = queryset.filter(user=user)
        # ПОИСК ПО ЗАГОЛОВКУ ИЛИ ОПИСАНИЮ:
        search = self.request.GET.get("search", "")
        if search:
            queryset = queryset.filter(
                Q(title__icontains=search) | Q(description__icontains=search)
            )
            return queryset
        else:
            return queryset


class EntryCreateView(LoginRequiredMixin, CreateView):
    """Создание записи"""

    model = Entry
    success_url = reverse_lazy("records:list")
    form_class = EntryCreateForm

    def form_valid(self, form):
        """Присвоение статуса записи, если запись является целью,
        по дате начала и конца"""

        entry = form.save()
        user = self.request.user
        entry.user = user

        now = datetime.now()
        if entry.is_purpose:
            if entry.end_time:
                if entry.end_time.date() < now.date():
                    entry.status = "PAST"
                elif entry.start_time.date() <= now.date():
                    entry.status = "PRESENT"
                else:
                    entry.status = "FUTURE"
            elif entry.start_time.date() <= now.date():
                entry.status = "PRESENT"
            else:
                entry.status = "FUTURE"
        entry.save()
        return super().form_valid(form)

    def get_success_url(self):
        entry_pk = self.object.pk
        return reverse_lazy("records:update", kwargs={"pk": entry_pk})


class EntryUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование записи"""

    model = Entry
    form_class = EntryUpdateForm

    def get_object(self, queryset=None):
        """Как только зашли на страницу редактирования записи,
        она получает статус последней просмотренной страницы"""

        object = super().get_object()
        for entry in Entry.objects.all():
            entry.last_viewed = False
            entry.save()
        entry = Entry.objects.get(pk=object.pk)
        entry.last_viewed = True
        entry.save()
        return object

    def form_valid(self, form):
        """Обновление статуса записи, если запись является целью,
        по дате начала и конца"""

        entry = form.save()
        user = self.request.user
        entry.user = user

        now = datetime.now()
        if entry.is_purpose:
            if entry.end_time:
                if entry.end_time.date() < now.date():
                    entry.status = "PAST"
                elif entry.start_time.date() <= now.date():
                    entry.status = "PRESENT"
                else:
                    entry.status = "FUTURE"
            elif entry.start_time.date() <= now.date():
                entry.status = "PRESENT"
            else:
                entry.status = "FUTURE"

        #  ДОБАВИТЬ ФОРМСЕТ:
        formset = self.get_context_data()["formset"]
        if formset.is_valid():
            formset.instance = entry
            formset.save()

        entry.save()
        return super().form_valid(form)

    def get_success_url(self):
        entry_pk = self.kwargs["pk"]
        return reverse_lazy("records:update", kwargs={"pk": entry_pk})

    def get_context_data(self, **kwargs):
        """Определяем формсет"""
        context_data = super().get_context_data(**kwargs)
        ObjectiveFormset = inlineformset_factory(
            Entry, Objective, form=ObjectiveForm, extra=0
        )
        if self.request.method == "POST":
            context_data["formset"] = ObjectiveFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = ObjectiveFormset(instance=self.object)

        return context_data


class EntryDetailView(LoginRequiredMixin, DetailView):
    """Просмотр записи"""

    model = Entry

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        entry = Entry.objects.get(pk=self.object.pk)
        objectives = Objective.objects.filter(entry=entry)
        context_data["objectives"] = objectives
        return context_data


class EntryDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление записи"""

    model = Entry
    success_url = reverse_lazy("records:list")


#  ЗАДАЧИ:
class ObjectiveCreateView(LoginRequiredMixin, CreateView):
    """Создание задачи"""

    model = Objective
    form_class = ObjectiveCreateForm

    def get_success_url(self):
        """Редиректит на страницу редактирования записи"""
        return reverse_lazy("records:update", kwargs={"pk": self.entry.pk})

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        entry = Entry.objects.get(last_viewed=True)
        context_data["entry_pk"] = entry.pk
        return context_data

    def form_valid(self, form):
        """Проверка валидности задачи"""
        objective = form.save()
        self.entry = Entry.objects.get(last_viewed=True)
        if self.entry.status == "PAST" and objective.is_complete is not True:
            raise Http404("Задачи к достигнутым целям должны считаться выполненными")
        objective.entry = self.entry
        objective.save()
        return super().form_valid(form)


class ObjectiveDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление задачи"""

    model = Objective
    template_name = "records/entry_confirm_delete.html"

    def get_success_url(self):
        objective_pk = self.kwargs["pk"]
        objective = Objective.objects.get(pk=objective_pk)
        return reverse_lazy("records:update", kwargs={"pk": objective.entry.pk})


class ObjectiveUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование задачи"""

    model = Objective
    form_class = ObjectiveCreateForm

    def get_success_url(self):
        """Редирект на страницу редактирования цели"""
        return reverse_lazy("records:update", kwargs={"pk": self.entry.pk})

    def form_valid(self, form):
        """Проверка валидности задачи"""
        objective = self.object
        self.entry = Entry.objects.get(last_viewed=True)
        if self.entry.status == "PAST" and not objective.is_complete:
            raise Http404("Задачи к достигнутым целям должны считаться выполненными")
        objective.entry = self.entry
        objective.save()
        return super().form_valid(form)

records/templates/records/entry_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}
</div>
</div>
</nav>
</header>
<head>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<style>
    body {
  background: url(/media/greenwood.jpg) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
</style>
<div class="row text-center mt-5">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <h3 class="font-bold mb-8">Удалить?</h3>
                    <button type="submit"
                            class="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                    >Подтвердить
                    </button>

                    <a class="btn text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                       href="{% url 'records:update' object.entry.pk %}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

records/templates/records/entry_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}
</div>
</div>
</nav>
</header>
<head>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<style>
    body {
  background: url(/media/greenwood.jpg) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
</style>
<div class="album py-5 bg-body-tertiary">
    <div class="col-12">
        <div class="container ">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col-6">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <h3 class="font-bold mb-8">{{ object.title}}</h3>
                            <p class="card-text">{{ object.description }}</p>
                            <p class="card-text">начало: {{object.start_time}} </p>
                            <p class="card-text">конец: {{object.end_time}}</p>
                            <p class="card-text">статус: {{object.status}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="row">
                                    <a class="btn text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l hover:from-teal-200 hover:to-lime-200 focus:ring-4 focus:outline-none focus:ring-lime-200 dark:focus:ring-teal-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                                       href="{% url 'records:update' object.pk %}">Редактировать</a>
                                    {% if object.is_private %}
                                    <a class="btn text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                                       href="{% url 'records:private_list' %}">Назад</a>
                                    {% elif object.status == 'PAST'%}
                                    <a class="btn text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                                       href="{% url 'records:past_list' %}">Назад</a>
                                    {% elif object.status == 'PRESENT'%}
                                    <a class="btn text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                                       href="{% url 'records:present_list' %}">Назад</a>
                                    {% elif object.status == 'FUTURE'%}
                                    <a class="btn text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                                       href="{% url 'records:future_list' %}">Назад</a>
                                    {% else %}
                                    <a class="btn text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                                       href="{% url 'records:list' %}">Назад</a>
                                    {% endif %}

                                    <a class="btn text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                                       href="{% url 'records:delete' object.pk %}">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            {% for objective in objectives %}
                            {% if objective.is_complete %}
                            <p><a class="icon-link icon-link-hover link-success link-underline-success link-underline-opacity-25"
                               href="{% url 'records:update_obj' objective.pk %}">
                                {{objective.title}}
                            </a>: {{objective.description}}</p>
                            {% else %}
                             <p><a class="icon-link icon-link-hover link-warning link-underline-success link-underline-opacity-25"
                               href="{% url 'records:update_obj' objective.pk %}">
                                {{objective.title}}
                            </a>: {{objective.description}}</p>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

records/templates/records/entry_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}
</div>
</div>
</nav>
</header>
<head>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<style>
    body {
  background: url(/media/greenwood.jpg) no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
</style>
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body ">
                    <h4 class="font-bold mb-8">Создание записи</h4>

                    {% csrf_token %}
                    {% crispy form %}
                    {% if object.pk %}
                    <a class="btn text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                       href="{% url 'records:detail' object.pk %}">Назад
                    </a>
                    {% else %}
                    <a class="btn text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                       href="{% url 'records:list' %}">Отмена
                    </a>
                    {% endif %}

                </div>
            </div>
        </div>
        {% if object.pk and object.is_purpose %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="font-bold mb-8">Задачи</h4>
                </div>
                {{ formset.management_form }}
                {% for form in formset.forms %}
                <div class="card-body ">
                    {% crispy form %}
                    <a class="btn text-white bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                       href="{% url 'records:update_obj' form.instance.pk %}">Редактировать</a>
                    <a class="btn text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                       href="{% url 'records:delete_obj' form.instance.pk %}">Удалить
                    </a>
                </div>
                {% endfor %}
                <a class="bnt text-gray-900 bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l hover:from-teal-200 hover:to-lime-200 focus:ring-4 focus:outline-none focus:ring-lime-200 dark:focus:ring-teal-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
               href="{% url 'records:create_obj' %}">Добавить задачу</a>

            </div>


        </div>
        {% endif %}
    </div>
</form>
{% endblock %}

records/templates/records/entry_list.html
{% extends 'base.html' %}

{% block content %}
{% include 'records/includes/inc_menu.html' %}
<div class="container marketing">
    <!-- Текст под каруселью -->
    <div class="row">
        {% for object in object_list %}
        <div class="col-lg-4">
            <a class="link text-dark" role="button" href="{% url 'records:detail' object.pk %}">
                {% if object.is_private %}
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="/media/lock.jpeg"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                </img>
                {% elif object.status == 'PAST'%}
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="/media/ok.png" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                </img>
                {% elif object.status == 'PRESENT'%}
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="/media/present.png" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                </img>
                {% elif object.status == 'FUTURE'%}
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="/media/future.png" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                </img>
                {% else %}
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="/media/entry.png" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                </img>
                {% endif %}
                <h2>{{object.title}}</h2>
            </a>
        </div><!-- /.col-lg-4 -->
        {% endfor %}
    </div><!-- /.row -->
</div><!-- /.container -->
{% endblock %}